version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - job-application-service
      - logging-service
    networks:
      - app-network

  job-application-service:
    build: ./Job-Application-Service
    networks:
      - app-network

  logging-service:
    build: ./Logging-Service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge